apiVersion: v1
kind: Service
metadata:
  name: backups-microservice
  namespace: statex-apps
  labels:
    app: backups-microservice
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: backups-microservice
  ports:
    - protocol: TCP
      port: 3398
      targetPort: 3398
      name: http
